# Generated by Django 4.1 on 2022-11-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banglore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=10)),
                ('Line1', models.IntegerField()),
                ('Line2', models.IntegerField()),
                ('Line3', models.IntegerField()),
                ('Line4', models.IntegerField()),
                ('Line5', models.IntegerField()),
            ],
        ),
    ]
