# Generated by Django 4.1 on 2022-11-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_date_banglore_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chennai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('line1', models.IntegerField()),
                ('line2', models.IntegerField()),
                ('line3', models.IntegerField()),
                ('line4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mumbai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('line1', models.IntegerField()),
                ('line2', models.IntegerField()),
                ('line3', models.IntegerField()),
            ],
        ),
    ]
